-- Sequence owning DDL orders
ALTER SEQUENCE transaction_table_id_seq OWNED BY transaction_table.id;
ALTER SEQUENCE ts_model_id_seq OWNED BY ts_model.id;
ALTER SEQUENCE file_table_id_seq OWNED BY file_table.id;
ALTER SEQUENCE program_id_seq OWNED BY program.id;
ALTER SEQUENCE tdqueue_id_seq OWNED BY tdqueue.id;
ALTER SEQUENCE ipconn_id_seq OWNED BY ipconn.id;
ALTER SEQUENCE mqconn_id_seq OWNED BY mqconn.id;
ALTER SEQUENCE enqmodel_id_seq OWNED BY enqmodel.id;
ALTER SEQUENCE scheduled_task_id_seq OWNED BY scheduled_task.id;
ALTER SEQUENCE tranclass_table_id_seq OWNED BY tranclass_table.id;

ALTER TABLE ONLY transaction_table ALTER COLUMN id SET DEFAULT nextval('transaction_table_id_seq'::regclass);
ALTER TABLE ONLY ts_model ALTER COLUMN id SET DEFAULT nextval('ts_model_id_seq'::regclass);
ALTER TABLE ONLY file_table ALTER COLUMN id SET DEFAULT nextval('file_table_id_seq'::regclass);
ALTER TABLE ONLY program ALTER COLUMN id SET DEFAULT nextval('program_id_seq'::regclass);
ALTER TABLE ONLY tdqueue ALTER COLUMN id SET DEFAULT nextval('tdqueue_id_seq'::regclass);
ALTER TABLE ONLY scheduled_task ALTER COLUMN id SET DEFAULT nextval('scheduled_task_id_seq'::regclass);
ALTER TABLE ONLY ipconn ALTER COLUMN id SET DEFAULT nextval('ipconn_id_seq'::regclass);
ALTER TABLE ONLY mqconn ALTER COLUMN id SET DEFAULT nextval('mqconn_id_seq'::regclass);
ALTER TABLE ONLY enqmodel ALTER COLUMN id SET DEFAULT nextval('enqmodel_id_seq'::regclass);
ALTER TABLE ONLY tranclass_table ALTER COLUMN id SET DEFAULT nextval('tranclass_table_id_seq'::regclass);

-- JICS tables setup
-- Generated from CICSDEFINITIONS.txt

INSERT INTO JICS_GROUP
	(NAME)
VALUES
	('TEST');

INSERT INTO JICS_LIST
	(LIST, IS_ACTIVE)
VALUES
	('TEST_LIST', TRUE);

INSERT INTO JICS_LIST_GROUP_LIST
	(JICS_LIST, GROUP_NAME)
VALUES
	('TEST_LIST', 'TEST');

INSERT INTO TRANSACTION_TABLE
	(GROUP_FK, TRANSACTION_COL, DESCRIPTION, ACTION_COL, ALIAS_COL, BREXIT, CMD_SEC, CONF_DATA, D_TIMOUT, DUMP_COL, DYNAMIC_COL, ISOLATE, LOCALQ, OTS_TIMEOUT, PRIORITY, PARTITION_SET, PROFILE, PROGRAM, REMOTE_SYSTEM, REMOTE_NAME, RES_SEC, RESTART, ROUTABLE, RUNAWAY, SHUTDOWN_COL, SPURGE, STATUS, STORAGE_CLEAR, TASK_DATA_KEY, TASK_DATA_LOC, TASK_REQ, TP_NAME, TPURGE, TRACE, TRAN_CLASS, TR_PROF, TWA_SIZE, WAIT, WAIT_TIME, XTP_NAME, XTRAN_ID, CHANGE_AGENT, CHANGE_AGREL, CHANGE_USR_ID, CHANGE_TIME, DEFINE_TIME)
VALUES
	('TEST', 'PINQ', ' ', NULL, NULL, NULL, FALSE, FALSE, 'NO', TRUE, FALSE, TRUE, FALSE, NULL, NULL, NULL, NULL, 'PLANETSINQ', NULL, NULL, FALSE, FALSE, FALSE, NULL, NULL, FALSE, NULL, FALSE, NULL, NULL, NULL, NULL, FALSE, TRUE, NULL, NULL, '0', TRUE, '0,0,0', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO PROGRAM
	(GROUP_FK, PROGRAM, DESCRIPTION, API, CEDF, DATA_LOCATION, DYNAMIC_COL, EXECUTION_SET, JVM, LANGUAGE_COL, CONCURRENCY, EXEC_KEY, RELOAD, RESIDENT, USAGE_COL, USE_LPA_COPY, JVM_SERVER, JVM_CLASS, REMOTE_SYSTEM, REMOTE_NAME, IS_STATUS_ENABLED, TRANS_ID, USE_SVA_COPY, CHANGE_AGENT, CHANGE_AGREL, CHANGE_USR_ID, CHANGE_TIME, DEFINE_TIME)
VALUES
	('TEST', 'PLANETSINQ', ' ', NULL, TRUE, NULL, FALSE, NULL, FALSE, 'COBOL', NULL, NULL, FALSE, FALSE, 'NORMAL', FALSE, NULL, NULL, NULL, NULL, TRUE, NULL, FALSE, NULL, NULL, NULL, NULL, NULL);
